import type { NextPage } from "next";
import Head from "next/head";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	return (
		<div className="">
			<Head>
				<title>TerraSystem - Soluçoes Tecnologicas</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<NavBar />
			</main>

			<Footer />
		</div>
	);
};

export default Home;
